"""rename address

Revision ID: 91de42913e65
Revises: 3565a928ba32
Create Date: 2024-10-02 15:37:32.238030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91de42913e65'
down_revision = '3565a928ba32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.String(), nullable=False))
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
